[package]
name = "muoxi_clients"
version = "0.1.0"
authors = ["duysqubix <duys@qubixat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = 'muoxi_client'
path = "src/main.rs"

[dependencies]
ws = "^0.9"
